sudo: false
language: python
dist: trusty
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip
  - PIP_FIND_LINKS=$HOME/.cache/pip
python:
- "3.5"
- "3.6"
- "3.7"
cache:
  directories:
  - $HOME/.cache/pip/
install:
- pip install -U pip
- pip install -e .[test]
script:
- python -m pytest -v --cov jsonseq --cov-report term-missing
after_success:
- coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: seang
